services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    container_name: numero-auth
    ports:
      - '5556:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=auth
